// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Yshu8432kAR4UpaE1Bj3fZmCDMQE9XY',
    appId: '1:53206696289:web:96312120888abff7890520',
    messagingSenderId: '53206696289',
    projectId: 'task-authentication-db',
    authDomain: 'task-authentication-db.firebaseapp.com',
    storageBucket: 'task-authentication-db.appspot.com',
    measurementId: 'G-FMY6FBJH7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZyBtzRHGtv438q905h6p_oSYbJJr8z0',
    appId: '1:53206696289:android:ae70ee599db69d93890520',
    messagingSenderId: '53206696289',
    projectId: 'task-authentication-db',
    storageBucket: 'task-authentication-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9m5cNIkN5WC_OiTmVIiFCPym7A90nAQw',
    appId: '1:53206696289:ios:bd2ff60ff2ca352d890520',
    messagingSenderId: '53206696289',
    projectId: 'task-authentication-db',
    storageBucket: 'task-authentication-db.appspot.com',
    iosBundleId: 'com.example.deepakKumarTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9m5cNIkN5WC_OiTmVIiFCPym7A90nAQw',
    appId: '1:53206696289:ios:9f9d2553d92faa8b890520',
    messagingSenderId: '53206696289',
    projectId: 'task-authentication-db',
    storageBucket: 'task-authentication-db.appspot.com',
    iosBundleId: 'com.example.deepakKumarTask.RunnerTests',
  );
}
